### ISSUE TITLE
Update Debezium and its implementation.

### ISSUE THREAD

**Issue by Stonepreheim** [spring-cloud/stream-applications#307] opened 2022-06-08 18:42 UTC
Hello, our team has noticed that this project is using Debezium 1.7 and should update to 1.9 as soon as possible. This project is also using this depreciated implementation: https://debezium.io/documentation/reference/1.9/operations/embedded.html. The internal API in use is subject to backwards incompatible change and needs to be switched for this instead: https://debezium.io/documentation/reference/1.9/development/engine.html.

**Comment by onobc** [comment] 2022-06-08 20:19
Hi @Stonepreheim ,

We are going to update it (see #188). We wanted to get it into the latest release `2021.1.2` but the changes turned out to be quite large. We will get it updated in the next release `2022.0.0` which will be based on SB3/SF6. This will be towards the end of 2022. 

Closing this now as duplicate of #188.

**Closed by onobc** 2022-06-08 20:19 UTC
