### ISSUE TITLE
Make all Configuration "proxyBeanMethods = false"

### ISSUE THREAD

**Issue by onobc** [spring-cloud/stream-applications#224] opened 2022-01-28 20:36 UTC
It is recommended to disable inter-bean methods in Configuration classes unless it is needed. 

This can improve startup time and also lead to cleaner bean methods using constructor injection and bean method parameter injection. 

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Configuration.html#proxyBeanMethods--

**Comment by artembilan** [comment] 2022-01-28 20:54
Sorry. Duplicate of https://github.com/spring-cloud/stream-applications/issues/106 😄

**Closed by artembilan** 2022-01-28 20:54 UTC
